### ISSUE TITLE
Line 1338 cause program to not run

### ISSUE THREAD

**Issue by katlou** [alexcoll/PhysPro-Nspire#6]
Program does not run on Ti-Nspire CX with error:

> Line 1338:
> 
> Bad argument #3 to '?' (string expected, got function)

**Comment by katlou** [comment]
Resolved by changing api to 2.0.

**Comment by rlrobman123** [comment]
I'm having this issue on the CX CAS ver. 4.2. How exactly did you resolve this issue?

**Comment by katlou** [comment]
@rlrobman123 There's a line in the code (I believe it is one of the first lines) that specifies the api version (`api_version = 1.0` or something like that, sorry I'm on mobile). I fixed the issue by changing it to 2.0.

**Comment by deepc0py** [comment]
@katlou I'm facing the same issue but am unable to edit the TNS file as I lost my activation key when changing computers. Any way I can get that changed version? Thank you.

**Comment by katlou** [comment]
@tylerjheslop So sorry, I also switched computers. I will ping you if I find it, but I'm in a busy stretch and don't have access to my old files. Best of luck!
